from distutils.core import setup
setup(name='brainsvg',
      version='0.0.1',
      install_requires = ['numpy',
                          'gdist',
                          'nibabel',
                          'scipy',
                          'xml',
                          'pandas',
                          'matplotlib',
                          'colormap',
                          'networkx',
                          'surfdist'],
      description='Package for creating brain-related svg illustrations based on data',
      url='http://github.com/margulies/brainsvg',
      author='margulies',
      author_email='daniel.margulies@gmail.com',
      license='MIT',
      packages=['brainsvg'],
      zip_safe=False)
